name: PYPE
channels:
  - defaults
  - conda-forge
  - bioconda
dependencies:
  - python
  - statsmodels
  - adjusttext
  - tqdm
  - seaborn
  - beautifulsoup4
  - charset-normalizer
  - scikit-learn
  - pandas
  - anaconda::chardet
  - requests
  - pip
  - pip:
    - mygene
    - myvariant
    - ieugwaspy